Repository ttodam-ttodam/ttodam-ttodam-BE, pull requests merged in 2024-04, with the labels that each got.

#16 Feature/#15 social
  .gitignore
  build.gradle
  src/main/java/com/ttodampartners/ttodamttodam/ServletInitializer.java
  src/main/java/com/ttodampartners/ttodamttodam/TtodamTtodamApplication.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/GoogleRedirectController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/ImageUpdateController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/KakaoRedirectController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/ProfileEditController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/ProfileUpdateController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/SigninController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/SignupController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/SocialController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/WithdrawController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/dto/ProfileDto.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/dto/SigninRequestDto.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/dto/SignupRequestDto.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/dto/model/BaseEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/entity/UserEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/exception/AwsException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/exception/CoordinateException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/exception/UserException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/repository/UserRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/AuthenticationService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/ImageUpdateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/ProfileEditService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/ProfileUpdateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/SigninService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/SignupService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/SocialService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/WithdrawService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/util/AuthenticationUtil.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/util/CoordinateFinderUtil.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/aws/S3Config.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/redis/RedisRepositoryConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/PasswordConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/SecurityConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/TokenProvider.java
  src/main/java/com/ttodampartners/ttodamttodam/global/dto/UserDetailsDto.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/GlobalExceptionHandler.java
  src/main/java/com/ttodampartners/ttodamttodam/global/util/RedisUtil.java
  src/main/java/com/ttodampartners/ttodamttodam/infra/email/controller/CodeConfirmController.java
  src/main/java/com/ttodampartners/ttodamttodam/infra/email/controller/MailSendController.java
  src/main/java/com/ttodampartners/ttodamttodam/infra/email/exception/MailException.java
  src/main/java/com/ttodampartners/ttodamttodam/infra/email/service/CodeConfirmService.java
  src/main/java/com/ttodampartners/ttodamttodam/infra/email/service/MailSendService.java
  src/main/resources/application.properties
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/GoogleRedirectControllerTest.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/KakaoRedirectControllerTest.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/SocialControllerTest.java
Labels: 기능

#19 Refartor/#18 password encoder
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/GoogleRedirectController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/KakaoRedirectController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/SocialController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/SocialService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/PasswordConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/SecurityConfig.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/GoogleRedirectControllerTest.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/KakaoRedirectControllerTest.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/SocialControllerTest.java
Labels: 수정

#12 Feature/#2 WebSocket 연결과 채팅방 생성 구현
  build.gradle
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/ChatResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatroomCreateRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/ChatroomResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/ChatroomResponseProfile.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatBaseEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatMessageEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatroomEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatroomMemberEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatroomMemberRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomService.java
  src/main/resources/application.properties
Labels: 기능

#30 Feature/#28 logout
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/controller/LogoutController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/LogoutService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/TokenProvider.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/util/RedisUtil.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/user/controller/LogoutControllerTest.java
Labels: 기능

#34 Fix/#27 개인 채팅방 중복 생성 방지 및 기타 exception 처리
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/ChatExceptionResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatroomCreateRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/ChatroomExistedResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/exception/ChatroomException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/exception/ChatroomStringException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatroomMemberRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/AuthenticationService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/TokenProvider.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/GlobalExceptionHandler.java
Labels: 수정

#56 Fix/#25 Stomp 이용시 JWT 유효성 검사 추가
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompHandler.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatroomCreateRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/StompExceptionResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatroomMemberEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/exception/StompException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomLeaveService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/SecurityConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomServiceTest.java
Labels: 수정

#61 Feature/#55 단체 채팅방 생성 구현
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/event/GroupChatCreateEvent.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/request/service/RequestService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
Labels: 기능

#63 Refactor/#62 채팅방 생성/조회 리팩토링
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/user/service/AuthenticationService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/GlobalExceptionHandler.java
  src/test/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateServiceTest.java
Labels: 수정

#71 Feature/#35 STOMP + JWT 에러 처리
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompExceptionHandler.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/config/StompHandler.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/StompExceptionResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/exception/ChatroomStringException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/exception/StompException.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomEnterService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/SecurityConfig.java
  src/main/java/com/ttodampartners/ttodamttodam/global/dto/UserDetailsDto.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/GlobalExceptionHandler.java
Labels: 수정

#72 [#35] feat: 단체 채팅방 생성시 알림 전송 기능 구현
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/notification/entity/NotificationEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/notification/service/NotificationService.java
Labels: 기능

#87 Refactor/#35 채팅방 생성/조회/나가기 관련 일부 오류 수정
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomEnterController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/dto/response/ChatroomListResponse.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatroomMemberEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomLeaveService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/notification/entity/NotificationEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/notification/service/NotificationService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/notification/service/NotificationViewService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/config/security/SecurityConfig.java
Labels: 수정

#92 Refactor/#35 채팅방 나가기 기능 업데이트 및 오류 수정
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/controller/ChatroomController.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/entity/ChatroomEntity.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomCreateService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomEnterService.java
  src/main/java/com/ttodampartners/ttodamttodam/domain/chat/service/ChatroomLeaveService.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/ErrorCode.java
  src/main/java/com/ttodampartners/ttodamttodam/global/error/GlobalExceptionHandler.java
Labels: 기능, 수정
